Repository Paris-Squad-S2/Aflami, pull requests merged in 2025-07, with the labels that each got.

#20 refactor Introduce search remote datasource module
  .github/workflows/cd-firebase-app-distribution.yml
  datasource/remote/search/.gitignore
  datasource/remote/search/build.gradle.kts
  datasource/remote/search/consumer-rules.pro
  datasource/remote/search/proguard-rules.pro
  datasource/remote/search/src/androidTest/java/com/example/search/ExampleInstrumentedTest.kt
  datasource/remote/search/src/main/AndroidManifest.xml
  datasource/remote/search/src/main/java/com/example/search/GenresRemoteDataSource.kt
  datasource/remote/search/src/main/java/com/example/search/GenresRemoteDataSourceImp.kt
  datasource/remote/search/src/main/java/com/example/search/SearchRemoteDataSource.kt
  datasource/remote/search/src/main/java/com/example/search/SearchRemoteDataSourceImpl.kt
  datasource/remote/search/src/main/java/com/example/search/api/GenresApiServices.kt
  datasource/remote/search/src/main/java/com/example/search/api/KtorGenresApiServices.kt
  datasource/remote/search/src/main/java/com/example/search/api/KtorSearchApiService.kt
  datasource/remote/search/src/main/java/com/example/search/api/SearchApiService.kt
  datasource/remote/search/src/main/java/com/example/search/di/SearchModule.kt
  datasource/remote/search/src/main/java/com/example/search/mapper/SearchMapper.kt
  datasource/remote/search/src/main/java/com/example/search/models/GenreDto.kt
  datasource/remote/search/src/main/java/com/example/search/models/KnownForDto.kt
  datasource/remote/search/src/main/java/com/example/search/models/ResultDto.kt
  datasource/remote/search/src/main/java/com/example/search/models/SearchDto.kt
  datasource/remote/search/src/test/java/com/example/search/ExampleUnitTest.kt
  feature/search/searchUi/build.gradle.kts
  feature/search/searchUi/src/main/java/com/feature/search/searchUi/SearchApp.kt
  feature/search/searchUi/src/main/java/com/feature/search/searchUi/di/NetworkModule.kt
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: feature

#37 Fix firebase app distribution
  .github/workflows/cd-firebase-app-distribution.yml
  app/build.gradle.kts
  app/src/main/java/com/paris_2/aflami/MainActivity.kt
  feature/search/searchUi/build.gradle.kts
  feature/search/searchUi/src/main/AndroidManifest.xml
  feature/search/searchUi/src/main/res/mipmap-anydpi/ic_launcher.xml
  feature/search/searchUi/src/main/res/mipmap-anydpi/ic_launcher_round.xml
  feature/search/searchUi/src/main/res/mipmap-hdpi/ic_launcher.webp
  feature/search/searchUi/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  feature/search/searchUi/src/main/res/mipmap-mdpi/ic_launcher.webp
  feature/search/searchUi/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  feature/search/searchUi/src/main/res/mipmap-xhdpi/ic_launcher.webp
  feature/search/searchUi/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  feature/search/searchUi/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  feature/search/searchUi/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  feature/search/searchUi/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  feature/search/searchUi/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
Labels: fix

#43 refactor: Improve search experience and UI and fix an illustration
  .github/workflows/cd-firebase-app-distribution.yml
  app/build.gradle.kts
  buildSrc/src/main/kotlin/Configurations.kt
  domain/search/src/main/java/com/domain/search/useCases/GetCountryCodeByNameUseCase.kt
  feature/search/searchUi/src/main/java/com/feature/search/searchUi/screen/findByActor/FindByActorViewModel.kt
  feature/search/searchUi/src/main/java/com/feature/search/searchUi/screen/search/SearchViewModel.kt
  feature/search/searchUi/src/main/java/com/feature/search/searchUi/screen/search/components/NoSearchQueryContent.kt
  feature/search/searchUi/src/main/java/com/feature/search/searchUi/screen/worldTour/WorldTourScreen.kt
  feature/search/searchUi/src/main/java/com/feature/search/searchUi/screen/worldTour/WorldTourViewModel.kt
  feature/search/searchUi/src/main/res/values-ar/strings.xml
  feature/search/searchUi/src/main/res/values/strings.xml
  feature/search/searchUi/src/test/java/com/feature/search/searchUi/screen/findByActor/FindByActorViewModelTest.kt
  feature/search/searchUi/src/test/java/com/feature/search/searchUi/screen/worldTour/WorldTourViewModelTest.kt
Labels: refactor

#42 refactor: Introduce animated TabRow component
  app/build.gradle.kts
  designsystem/src/main/java/com/paris_2/aflami/designsystem/components/AflamiTabs.kt
  feature/search/searchUi/src/main/java/com/feature/search/searchUi/comon/components/SearchResultContent.kt
  feature/search/searchUi/src/main/java/com/feature/search/searchUi/screen/search/components/WithSearchQueryContent.kt
Labels: refactor design component

#41 bug-fix: fix Update category filter reset logic
  .github/workflows/cd-firebase-app-distribution.yml
  app/build.gradle.kts
  feature/search/searchUi/src/main/java/com/feature/search/searchUi/screen/search/SearchViewModel.kt
Labels: bug-fix

#44 bugfix/fix-safe-image-viewer
  .github/workflows/cd-firebase-app-distribution.yml
  app/build.gradle.kts
  app/proguard-rules.pro
  designsystem/build.gradle.kts
  designsystem/src/main/java/com/paris_2/aflami/designsystem/components/AflamiMediaCard.kt
  feature/search/searchUi/src/main/java/com/feature/search/searchUi/comon/components/SearchResultContent.kt
  safeimageviewer/build.gradle.kts
  safeimageviewer/src/main/java/com/designSystem/safeimageviewer/NSFWCache.kt
  safeimageviewer/src/main/java/com/designSystem/safeimageviewer/SafeImageViewer.kt
  safeimageviewer/src/main/java/com/designSystem/safeimageviewer/algorithm/FastBlurBitmap.kt
  safeimageviewer/src/main/java/com/designSystem/safeimageviewer/modifier/FastBlurModifier.kt
Labels: enhancement, fix

#48 Add domain models, repositories, and use cases for media details
  .github/workflows/cd-firebase-app-distribution.yml
  app/release-info.txt
  domain/mediaDetails/.gitignore
  domain/mediaDetails/build.gradle.kts
  domain/mediaDetails/src/main/java/com/domain/mediaDetails/model/Cast.kt
  domain/mediaDetails/src/main/java/com/domain/mediaDetails/model/Country.kt
  domain/mediaDetails/src/main/java/com/domain/mediaDetails/model/Episode.kt
  domain/mediaDetails/src/main/java/com/domain/mediaDetails/model/Gallery.kt
  domain/mediaDetails/src/main/java/com/domain/mediaDetails/model/Genre.kt
  domain/mediaDetails/src/main/java/com/domain/mediaDetails/model/Image.kt
  domain/mediaDetails/src/main/java/com/domain/mediaDetails/model/Movie.kt
  domain/mediaDetails/src/main/java/com/domain/mediaDetails/model/ProductionCompany.kt
  domain/mediaDetails/src/main/java/com/domain/mediaDetails/model/Review.kt
  domain/mediaDetails/src/main/java/com/domain/mediaDetails/model/Season.kt
  domain/mediaDetails/src/main/java/com/domain/mediaDetails/model/TvShow.kt
  domain/mediaDetails/src/main/java/com/domain/mediaDetails/repository/MovieRepository.kt
  domain/mediaDetails/src/main/java/com/domain/mediaDetails/repository/TvShowRepository.kt
  domain/mediaDetails/src/main/java/com/domain/mediaDetails/useCases/movie/AddMovieToFavoriteUseCase.kt
  domain/mediaDetails/src/main/java/com/domain/mediaDetails/useCases/movie/AddMovieToListUseCase.kt
  domain/mediaDetails/src/main/java/com/domain/mediaDetails/useCases/movie/GetMovieCastUseCase.kt
  domain/mediaDetails/src/main/java/com/domain/mediaDetails/useCases/movie/GetMovieDetailsUseCase.kt
  domain/mediaDetails/src/main/java/com/domain/mediaDetails/useCases/movie/GetMovieMediaUseCase.kt
  domain/mediaDetails/src/main/java/com/domain/mediaDetails/useCases/movie/GetMovieReviewsUseCase.kt
  domain/mediaDetails/src/main/java/com/domain/mediaDetails/useCases/movie/GetMoviesProductionCompaniesUseCase.kt
  domain/mediaDetails/src/main/java/com/domain/mediaDetails/useCases/tvShows/AddTvShowToFavoriteUseCase.kt
  domain/mediaDetails/src/main/java/com/domain/mediaDetails/useCases/tvShows/AddTvShowToListUseCase.kt
  domain/mediaDetails/src/main/java/com/domain/mediaDetails/useCases/tvShows/GetSeasonsUseCase.kt
  domain/mediaDetails/src/main/java/com/domain/mediaDetails/useCases/tvShows/GetTvShowCastUseCase.kt
  domain/mediaDetails/src/main/java/com/domain/mediaDetails/useCases/tvShows/GetTvShowDetailsUseCase.kt
  domain/mediaDetails/src/main/java/com/domain/mediaDetails/useCases/tvShows/GetTvShowMediaUseCase.kt
  domain/mediaDetails/src/main/java/com/domain/mediaDetails/useCases/tvShows/GetTvShowReviewsUseCase.kt
  domain/mediaDetails/src/main/java/com/domain/mediaDetails/useCases/tvShows/GetTvShowsProductionCompaniesUseCase.kt
  settings.gradle.kts
Labels: enhancement, feature

#54 fix Firebase App Distribution
  .github/workflows/cd-firebase-app-distribution.yml
  app/build.gradle.kts
  app/release-info.txt
Labels: fix, bug-fix

#71 bugfix/fix-change-language
  app/release-info.txt
  datasource/local/search/src/main/java/com/datasource/local/search/dao/MediaDao.kt
  datasource/local/search/src/main/java/com/datasource/local/search/datasource/MediaLocalDataSourceImpl.kt
  datasource/local/search/src/test/java/com/datasource/local/search/datasource/CountriesLocalDataSourceImplTest.kt
  datasource/local/search/src/test/java/com/datasource/local/search/datasource/MediaLocalDataSourceImplTest.kt
  domain/search/src/main/java/com/domain/search/model/Country.kt
  domain/search/src/main/java/com/domain/search/useCases/AutoCompleteCountryUseCase.kt
  domain/search/src/main/java/com/domain/search/useCases/GetCountryCodeByNameUseCase.kt
  domain/search/src/test/java/com/domain/search/useCases/AutoCompleteCountryUseCaseTest.kt
  domain/search/src/test/java/com/domain/search/useCases/GetCountryCodeByNameUseCaseTest.kt
  domain/search/src/test/java/testUtils/testUtils.kt
  feature/search/searchUi/src/main/java/com/feature/search/searchUi/screen/search/SearchViewModel.kt
  feature/search/searchUi/src/main/java/com/feature/search/searchUi/screen/search/components/NoSearchQueryContent.kt
  feature/search/searchUi/src/main/java/com/feature/search/searchUi/screen/worldTour/WorldTourScreen.kt
  feature/search/searchUi/src/main/java/com/feature/search/searchUi/screen/worldTour/WorldTourViewModel.kt
  feature/search/searchUi/src/main/res/values-ar/strings.xml
  feature/search/searchUi/src/main/res/values/strings.xml
  feature/search/searchUi/src/test/java/com/feature/search/searchUi/screen/worldTour/WorldTourViewModelTest.kt
  repository/search/src/main/java/com/repository/search/dataSource/local/MediaLocalDataSource.kt
  repository/search/src/main/java/com/repository/search/entity/CountryEntity.kt
  repository/search/src/main/java/com/repository/search/entity/MediaEntity.kt
  repository/search/src/main/java/com/repository/search/mapper/CountryMapper.kt
  repository/search/src/main/java/com/repository/search/mapper/SearchMediaMapper.kt
  repository/search/src/main/java/com/repository/search/repository/SearchMediaRepositoryImpl.kt
  repository/search/src/main/java/com/repository/search/util/Util.kt
  repository/search/src/test/kotlin/com/repository/search/repository/CountryRepositoryImplTest.kt
  repository/search/src/test/kotlin/com/repository/search/repository/SearchMediaRepositoryImplTest.kt
Labels: bug, enhancement, bug-fix

#73 bugfix search by country code
  app/release-info.txt
  domain/search/src/main/java/com/domain/search/useCases/GetCountryCodeByNameUseCase.kt
Labels: bug, documentation, bug-fix

#90 Feature/authentication ui
  app/release-info.txt
  app/src/main/java/com/paris_2/aflami/di/FeaturesApiModule.kt
  app/src/main/java/com/paris_2/aflami/di/UseCaseModule.kt
  app/src/main/java/com/paris_2/aflami/di/ViewModelModule.kt
  build.gradle.kts
  datasource/remote/authentication/src/main/java/com/paris_2/datasource/remote/authentication/AuthenticationRemoteDataSourceImpl.kt
  datasource/remote/authentication/src/test/java/com/paris_2/datasource/remote/authentication/AuthenticationRemoteDataSourceImplTest.kt
  designsystem/src/main/java/com/paris_2/aflami/designsystem/color/DarkThemeColors.kt
  designsystem/src/main/java/com/paris_2/aflami/designsystem/color/LightThemeColors.kt
  designsystem/src/main/java/com/paris_2/aflami/designsystem/components/SnackBar.kt
  designsystem/src/main/java/com/paris_2/aflami/designsystem/components/TextFields.kt
  designsystem/src/main/res/values-ar/strings.xml
  designsystem/src/main/res/values/strings.xml
  domain/authentication/src/main/java/com/paris_2/domain/authentication/exception/AuthException.kt
  domain/authentication/src/main/java/com/paris_2/domain/authentication/repository/AuthenticationRepository.kt
  domain/authentication/src/main/java/com/paris_2/domain/authentication/usecases/GetForgetPasswordUrlUseCase.kt
  domain/authentication/src/main/java/com/paris_2/domain/authentication/usecases/GetRegisterUrlUseCase.kt
  feature/authentication/authenticationApi/src/main/java/com/feature/authentication/authenticationApi/AuthenticationDestinations.kt
  feature/authentication/authenticationUi/build.gradle.kts
  feature/authentication/authenticationUi/src/main/java/com/feature/authentication/authenticationUi/AuthenticationFeatureAPIImpl.kt
  feature/authentication/authenticationUi/src/main/java/com/feature/authentication/authenticationUi/comon/BaseViewModel.kt
  feature/authentication/authenticationUi/src/main/java/com/feature/authentication/authenticationUi/comon/WebViewClientImpl.kt
  feature/authentication/authenticationUi/src/main/java/com/feature/authentication/authenticationUi/comon/WebViewComposable.kt
  feature/authentication/authenticationUi/src/main/java/com/feature/authentication/authenticationUi/navigation/AuthenticationNavGraph.kt
  feature/authentication/authenticationUi/src/main/java/com/feature/authentication/authenticationUi/navigation/AuthenticationNavigationEvent.kt
  feature/authentication/authenticationUi/src/main/java/com/feature/authentication/authenticationUi/navigation/Navigator.kt
  feature/authentication/authenticationUi/src/main/java/com/feature/authentication/authenticationUi/navigation/NavigatorImpl.kt
  feature/authentication/authenticationUi/src/main/java/com/feature/authentication/authenticationUi/navigation/ObserveAsEvents.kt
  feature/authentication/authenticationUi/src/main/java/com/feature/authentication/authenticationUi/screen/forgotPassword/ForgotPasswordUIState.kt
  feature/authentication/authenticationUi/src/main/java/com/feature/authentication/authenticationUi/screen/forgotPassword/ForgotPasswordViewModel.kt
  feature/authentication/authenticationUi/src/main/java/com/feature/authentication/authenticationUi/screen/forgotPassword/ForgotPasswordWebViewScreen.kt
  feature/authentication/authenticationUi/src/main/java/com/feature/authentication/authenticationUi/screen/login/LoginScreen.kt
  feature/authentication/authenticationUi/src/main/java/com/feature/authentication/authenticationUi/screen/login/LoginScreenInteractionListener.kt
  feature/authentication/authenticationUi/src/main/java/com/feature/authentication/authenticationUi/screen/login/LoginUIState.kt
  feature/authentication/authenticationUi/src/main/java/com/feature/authentication/authenticationUi/screen/login/LoginViewModel.kt
  feature/authentication/authenticationUi/src/main/java/com/feature/authentication/authenticationUi/screen/login/components/CircleBackground.kt
  feature/authentication/authenticationUi/src/main/java/com/feature/authentication/authenticationUi/screen/login/components/HeaderIconLogin.kt
  feature/authentication/authenticationUi/src/main/java/com/feature/authentication/authenticationUi/screen/login/components/IconLogin.kt
  feature/authentication/authenticationUi/src/main/java/com/feature/authentication/authenticationUi/screen/register/RegisterUIState.kt
  feature/authentication/authenticationUi/src/main/java/com/feature/authentication/authenticationUi/screen/register/RegisterViewModel.kt
  feature/authentication/authenticationUi/src/main/java/com/feature/authentication/authenticationUi/screen/register/RegisterWebViewScreen.kt
  feature/authentication/authenticationUi/src/main/res/drawable/ic_eye.xml
  feature/authentication/authenticationUi/src/main/res/drawable/ic_password.xml
  feature/authentication/authenticationUi/src/main/res/drawable/ic_user.xml
  feature/authentication/authenticationUi/src/main/res/values-ar/strings.xml
  feature/authentication/authenticationUi/src/main/res/values/strings.xml
  feature/authentication/authenticationUi/src/test/java/com/feature/authentication/authenticationUi/comon/WebViewClientImplTest.kt
  feature/authentication/authenticationUi/src/test/java/com/feature/authentication/authenticationUi/screen/forgotPassword/ForgotPasswordViewModelTest.kt
  feature/authentication/authenticationUi/src/test/java/com/feature/authentication/authenticationUi/screen/login/LoginViewModelTest.kt
  feature/authentication/authenticationUi/src/test/java/com/feature/authentication/authenticationUi/screen/register/RegisterViewModelTest.kt
  gradle/libs.versions.toml
  repository/authentication/src/main/java/com/paris_2/repository/authentication/dataSource/remote/AuthenticationRemoteDataSource.kt
  repository/authentication/src/main/java/com/paris_2/repository/authentication/exeptions/AuthenticationExceptions.kt
  repository/authentication/src/main/java/com/paris_2/repository/authentication/repository/AuthenticationRepositoryImpl.kt
  repository/authentication/src/test/java/com/paris_2/repository/authentication/repository/AuthenticationRepositoryImplTest.kt
Labels: feature

#105 Refactor/repository unit tests
  app/release-info.txt
  repository/movie/src/test/java/com/repository/movie/repository/MovieRepositoryImplTest.kt
  repository/tvShows/src/test/java/com/repository/tvshow/repository/TvShowRepositoryImplTest.kt
Labels: refactor

#106 Refactor/separate view model state
  app/release-info.txt
  feature/search/searchUi/src/main/java/com/feature/search/searchUi/comon/BaseViewModel.kt
  feature/search/searchUi/src/main/java/com/feature/search/searchUi/comon/components/SearchResultContent.kt
  feature/search/searchUi/src/main/java/com/feature/search/searchUi/mapper/UiMapper.kt
  feature/search/searchUi/src/main/java/com/feature/search/searchUi/pagging/FindByActorPagingSource.kt
  feature/search/searchUi/src/main/java/com/feature/search/searchUi/pagging/SearchByQueryPagingSource.kt
  feature/search/searchUi/src/main/java/com/feature/search/searchUi/pagging/WorldTourPagingSource.kt
  feature/search/searchUi/src/main/java/com/feature/search/searchUi/screen/findByActor/FindByActorScreen.kt
  feature/search/searchUi/src/main/java/com/feature/search/searchUi/screen/findByActor/FindByActorScreenInteractionListener.kt
  feature/search/searchUi/src/main/java/com/feature/search/searchUi/screen/findByActor/FindByActorUiState.kt
  feature/search/searchUi/src/main/java/com/feature/search/searchUi/screen/findByActor/FindByActorViewModel.kt
  feature/search/searchUi/src/main/java/com/feature/search/searchUi/screen/search/SearchScreen.kt
  feature/search/searchUi/src/main/java/com/feature/search/searchUi/screen/search/SearchScreenInteractionListener.kt
  feature/search/searchUi/src/main/java/com/feature/search/searchUi/screen/search/SearchUiState.kt
  feature/search/searchUi/src/main/java/com/feature/search/searchUi/screen/search/SearchViewModel.kt
  feature/search/searchUi/src/main/java/com/feature/search/searchUi/screen/search/components/FilterDialog.kt
  feature/search/searchUi/src/main/java/com/feature/search/searchUi/screen/search/components/NoSearchQueryContent.kt
  feature/search/searchUi/src/main/java/com/feature/search/searchUi/screen/search/components/WithSearchQueryContent.kt
  feature/search/searchUi/src/main/java/com/feature/search/searchUi/screen/worldTour/WorldTourScreenInteractionListener.kt
  feature/search/searchUi/src/main/java/com/feature/search/searchUi/screen/worldTour/WorldTourUiState.kt
  feature/search/searchUi/src/main/java/com/feature/search/searchUi/screen/worldTour/WorldTourViewModel.kt
  feature/search/searchUi/src/test/java/com/feature/search/searchUi/screen/findByActor/FindByActorViewModelTest.kt
  feature/search/searchUi/src/test/java/com/feature/search/searchUi/screen/search/SearchViewModelTest.kt
  feature/search/searchUi/src/test/java/com/feature/search/searchUi/screen/utils/mapper.kt
  feature/search/searchUi/src/test/java/com/feature/search/searchUi/screen/worldTour/WorldTourViewModelTest.kt
Labels: refactor

#104 refactor/add-isLoggedIn
  app/release-info.txt
  app/src/main/java/com/paris_2/aflami/MainActivity.kt
  app/src/main/java/com/paris_2/aflami/di/FeaturesApiModule.kt
  app/src/main/java/com/paris_2/aflami/di/UseCaseModule.kt
  app/src/main/java/com/paris_2/aflami/di/ViewModelModule.kt
  datasource/local/authentication/build.gradle.kts
  datasource/local/authentication/src/main/java/com/paris_2/dataSource/local/authentication/AuthenticationLocalDataSourceImpl.kt
  datasource/local/authentication/src/test/java/com/paris_2/dataSource/local/authentication/AuthenticationLocalDataSourceImplTest.kt
  domain/authentication/build.gradle.kts
  domain/authentication/src/main/java/com/paris_2/domain/authentication/repository/AuthenticationRepository.kt
  domain/authentication/src/main/java/com/paris_2/domain/authentication/usecase/HasAnySessionUseCase.kt
  domain/authentication/src/main/java/com/paris_2/domain/authentication/usecase/IsLoggedInUseCase.kt
  domain/authentication/src/test/java/com/paris_2/domain/authentication/usecase/HasAnySessionUseCaseTest.kt
  domain/authentication/src/test/java/com/paris_2/domain/authentication/usecase/IsLoggedInUseCaseTest.kt
  domain/mediaDetails/build.gradle.kts
  domain/mediaDetails/src/main/java/com/domain/mediaDetails/repository/MovieRepository.kt
  domain/mediaDetails/src/main/java/com/domain/mediaDetails/repository/TvShowRepository.kt
  domain/mediaDetails/src/main/java/com/domain/mediaDetails/useCase/movie/AddRatingToMovieUseCase.kt
  domain/mediaDetails/src/main/java/com/domain/mediaDetails/useCase/tvShows/AddRatingToTvShowUseCase.kt
  domain/mediaDetails/src/test/java/com/domain/mediaDetails/useCase/movie/AddMovieToFavoriteUseCaseTest.kt
  domain/mediaDetails/src/test/java/com/domain/mediaDetails/useCase/movie/AddRatingToMovieUseCaseTest.kt
  domain/mediaDetails/src/test/java/com/domain/mediaDetails/useCase/movie/GetMovieCastUseCaseTest.kt
  domain/mediaDetails/src/test/java/com/domain/mediaDetails/useCase/movie/GetMovieDetailsUseCaseTest.kt
  domain/mediaDetails/src/test/java/com/domain/mediaDetails/useCase/movie/GetMovieGalleryUseCaseTest.kt
  domain/mediaDetails/src/test/java/com/domain/mediaDetails/useCase/movie/GetMovieRecommendationsUseCaseTest.kt
  domain/mediaDetails/src/test/java/com/domain/mediaDetails/useCase/movie/GetMovieReviewsUseCaseTest.kt
  domain/mediaDetails/src/test/java/com/domain/mediaDetails/useCase/movie/GetMovieVideoUseCaseTest.kt
  domain/mediaDetails/src/test/java/com/domain/mediaDetails/useCase/movie/GetMoviesProductionCompaniesUseCaseTest.kt
  domain/mediaDetails/src/test/java/com/domain/mediaDetails/useCase/tvShows/AddRatingToTvShowUseCaseTest.kt
  domain/mediaDetails/src/test/java/com/domain/mediaDetails/useCase/tvShows/AddTvShowToFavoriteUseCaseTest.kt
  domain/mediaDetails/src/test/java/com/domain/mediaDetails/useCase/tvShows/GetSeasonsUseCaseTest.kt
  domain/mediaDetails/src/test/java/com/domain/mediaDetails/useCase/tvShows/GetTvShowCastUseCaseTest.kt
  domain/mediaDetails/src/test/java/com/domain/mediaDetails/useCase/tvShows/GetTvShowDetailsUseCaseTest.kt
  domain/mediaDetails/src/test/java/com/domain/mediaDetails/useCase/tvShows/GetTvShowGalleryUseCaseTest.kt
  domain/mediaDetails/src/test/java/com/domain/mediaDetails/useCase/tvShows/GetTvShowRecommendationsUseCaseTest.kt
  domain/mediaDetails/src/test/java/com/domain/mediaDetails/useCase/tvShows/GetTvShowReviewsUseCaseTest.kt
  domain/mediaDetails/src/test/java/com/domain/mediaDetails/useCase/tvShows/GetTvShowVideoUseCaseTest.kt
  domain/mediaDetails/src/test/java/com/domain/mediaDetails/useCase/tvShows/GetTvShowsProductionCompaniesUseCaseTest.kt
  feature/authentication/authenticationUi/src/main/java/com/feature/authentication/authenticationUi/screen/login/LoginViewModel.kt
  feature/authentication/authenticationUi/src/test/java/com/feature/authentication/authenticationUi/screen/login/LoginViewModelTest.kt
  feature/mediaDetails/mediaDetailsUi/build.gradle.kts
  feature/mediaDetails/mediaDetailsUi/src/main/java/com/feature/mediaDetails/mediaDetailsUi/ui/comon/components/RatingDialog.kt
  feature/mediaDetails/mediaDetailsUi/src/main/java/com/feature/mediaDetails/mediaDetailsUi/ui/screen/movie/details/MovieDetailsScreen.kt
  feature/mediaDetails/mediaDetailsUi/src/main/java/com/feature/mediaDetails/mediaDetailsUi/ui/screen/movie/details/MovieDetailsScreenInteractionListener.kt
  feature/mediaDetails/mediaDetailsUi/src/main/java/com/feature/mediaDetails/mediaDetailsUi/ui/screen/movie/details/MovieDetailsViewModel.kt
  feature/mediaDetails/mediaDetailsUi/src/main/java/com/feature/mediaDetails/mediaDetailsUi/ui/screen/movie/details/MovieUiState.kt
  feature/mediaDetails/mediaDetailsUi/src/main/java/com/feature/mediaDetails/mediaDetailsUi/ui/screen/tvShow/details/TvShowDetailsScreen.kt
  feature/mediaDetails/mediaDetailsUi/src/main/java/com/feature/mediaDetails/mediaDetailsUi/ui/screen/tvShow/details/TvShowDetailsViewModel.kt
  feature/mediaDetails/mediaDetailsUi/src/main/java/com/feature/mediaDetails/mediaDetailsUi/ui/screen/tvShow/details/TvShowScreenInteractionListener.kt
  feature/mediaDetails/mediaDetailsUi/src/main/java/com/feature/mediaDetails/mediaDetailsUi/ui/screen/tvShow/details/TvShowUiState.kt
  feature/mediaDetails/mediaDetailsUi/src/test/java/com/feature/mediaDetails/mediaDetailsUi/ui/screen/details/MovieDetailsViewModelTest.kt
  feature/mediaDetails/mediaDetailsUi/src/test/java/com/feature/mediaDetails/mediaDetailsUi/ui/screen/details/TvShowDetailsViewModelTest.kt
  feature/mediaDetails/mediaDetailsUi/src/test/java/com/feature/mediaDetails/mediaDetailsUi/ui/screen/video/VideoWebViewViewModelTest.kt
  repository/authentication/src/main/java/com/paris_2/repository/authentication/dataSource/local/AuthenticationLocalDataSource.kt
  repository/authentication/src/main/java/com/paris_2/repository/authentication/repository/AuthenticationRepositoryImpl.kt
  repository/authentication/src/test/java/com/paris_2/repository/authentication/repository/AuthenticationRepositoryImplTest.kt
  repository/movie/src/main/java/com/repository/movie/repository/MovieRepositoryImpl.kt
  repository/tvShows/build.gradle.kts
  repository/tvShows/src/main/java/com/repository/repository/TvShowRepositoryImpl.kt
  repository/tvShows/src/test/java/com/repository/tvshow/repository/TvShowRepositoryImplTest.kt
Labels: fix, refactor

#121 refactor/fix-slider-issue
  app/release-info.txt
  designsystem/src/main/java/com/paris_2/aflami/designsystem/components/MediaCard.kt
  designsystem/src/main/java/com/paris_2/aflami/designsystem/components/Slider.kt
  designsystem/src/main/java/com/paris_2/aflami/designsystem/components/TopAppBar.kt
  designsystem/src/main/java/com/paris_2/aflami/designsystem/text_style/DefaultTextStyle.kt
  feature/home/homeUi/src/main/java/com/feature/home/homeUi/screen/home/HomeScreen.kt
  feature/home/homeUi/src/main/java/com/feature/home/homeUi/screen/home/components/HomeSlider.kt
  feature/home/homeUi/src/main/res/values-ar/strings.xml
  feature/home/homeUi/src/main/res/values/strings.xml
Labels: fix

#120 Solve Home Screen Issues
  app/release-info.txt
  designsystem/src/main/java/com/paris_2/aflami/designsystem/components/MoodPicker.kt
  designsystem/src/main/java/com/paris_2/aflami/designsystem/components/TopAppBar.kt
  designsystem/src/main/java/com/paris_2/aflami/designsystem/text_style/AflamiTextStyle.kt
  designsystem/src/main/java/com/paris_2/aflami/designsystem/text_style/DefaultTextStyle.kt
  feature/home/homeUi/src/main/java/com/feature/home/homeUi/screen/home/HomeScreen.kt
  feature/home/homeUi/src/main/java/com/feature/home/homeUi/screen/home/components/HomeSection.kt
  feature/home/homeUi/src/main/java/com/feature/home/homeUi/screen/home/components/HomeSlider.kt
  feature/home/homeUi/src/main/java/com/feature/home/homeUi/screen/home/components/MoodPickerDialog.kt
Labels: fix

#140 fix issue when click on season header
  feature/mediaDetails/mediaDetailsUi/src/main/java/com/feature/mediaDetails/mediaDetailsUi/ui/comon/components/seasonSection/SeasonHeader.kt
Labels: bug-fix

#174 Bug fix/fix some home design issues
  feature/home/homeUi/src/main/java/com/feature/home/homeUi/screen/home/HomeScreen.kt
  feature/home/homeUi/src/main/java/com/feature/home/homeUi/screen/home/components/HomeSlider.kt
Labels: bug-fix

#185 Bugfix/home screen click behavior
  app/release-info.txt
  feature/home/homeUi/src/main/java/com/feature/home/homeUi/screen/home/HomeScreen.kt
  feature/home/homeUi/src/main/java/com/feature/home/homeUi/screen/home/components/HomeSection.kt
Labels: bug-fix

#184 correct season retrieval by tvShowId and seasonNumber, update related data source and tests
  app/release-info.txt
  datasource/local/tvShow/src/main/java/com/datasource/local/dao/SeasonDao.kt
  datasource/local/tvShow/src/main/java/com/datasource/local/datasource/TvShowSeasonLocalDataSourceImp.kt
  datasource/local/tvShow/src/test/java/com/datasource/local/datasource/SeasonLocalDataSourceImpTest.kt
  designsystem/src/main/java/com/paris_2/aflami/designsystem/components/Chips.kt
  feature/mediaDetails/mediaDetailsUi/src/main/java/com/feature/mediaDetails/mediaDetailsUi/ui/comon/components/ChipsRowSection.kt
  repository/tvShows/src/main/java/com/repository/dataSource/local/TvShowSeasonLocalDataSource.kt
  repository/tvShows/src/main/java/com/repository/repository/TvShowRepositoryImpl.kt
  repository/tvShows/src/test/java/com/repository/tvshow/repository/TvShowRepositoryImplTest.kt
Labels: bug-fix

#188 refactor/paging-source-and-loading-state
  app/release-info.txt
  build.gradle.kts
  designsystem/src/main/java/com/paris_2/aflami/designsystem/components/Slider.kt
  feature/home/homeUi/src/main/java/com/feature/home/homeUi/screen/home/HomeScreen.kt
  feature/home/homeUi/src/main/java/com/feature/home/homeUi/screen/home/HomeScreenViewModel.kt
  feature/home/homeUi/src/main/java/com/feature/home/homeUi/screen/home/components/HomeSection.kt
  feature/home/homeUi/src/main/java/com/feature/home/homeUi/screen/home/components/HomeSlider.kt
  feature/mediaDetails/mediaDetailsUi/src/main/java/com/feature/mediaDetails/mediaDetailsUi/ui/paging/PagingSource.kt
  feature/mediaDetails/mediaDetailsUi/src/main/java/com/feature/mediaDetails/mediaDetailsUi/ui/paging/ReviewMoviePagingSource.kt
  feature/mediaDetails/mediaDetailsUi/src/main/java/com/feature/mediaDetails/mediaDetailsUi/ui/paging/ReviewTvShowPagingSource.kt
  feature/mediaDetails/mediaDetailsUi/src/main/java/com/feature/mediaDetails/mediaDetailsUi/ui/paging/SimilarMoviePageSource.kt
  feature/mediaDetails/mediaDetailsUi/src/main/java/com/feature/mediaDetails/mediaDetailsUi/ui/paging/SimilarTvShowPageSource.kt
  feature/mediaDetails/mediaDetailsUi/src/main/java/com/feature/mediaDetails/mediaDetailsUi/ui/screen/movie/details/MovieDetailsViewModel.kt
  feature/mediaDetails/mediaDetailsUi/src/main/java/com/feature/mediaDetails/mediaDetailsUi/ui/screen/tvShow/details/TvShowDetailsViewModel.kt
  feature/mediaDetails/mediaDetailsUi/src/test/java/com/feature/mediaDetails/mediaDetailsUi/ui/screen/details/MovieDetailsViewModelTest.kt
  feature/mediaDetails/mediaDetailsUi/src/test/java/com/feature/mediaDetails/mediaDetailsUi/ui/screen/details/TvShowDetailsViewModelTest.kt
  feature/search/searchUi/src/main/java/com/feature/search/searchUi/pagging/FindByActorPagingSource.kt
  feature/search/searchUi/src/main/java/com/feature/search/searchUi/pagging/PagingSource.kt
  feature/search/searchUi/src/main/java/com/feature/search/searchUi/pagging/SearchByQueryPagingSource.kt
  feature/search/searchUi/src/main/java/com/feature/search/searchUi/pagging/WorldTourPagingSource.kt
  feature/search/searchUi/src/main/java/com/feature/search/searchUi/screen/findByActor/FindByActorViewModel.kt
  feature/search/searchUi/src/main/java/com/feature/search/searchUi/screen/search/SearchViewModel.kt
  feature/search/searchUi/src/main/java/com/feature/search/searchUi/screen/worldTour/WorldTourViewModel.kt
  feature/search/searchUi/src/test/java/com/feature/search/searchUi/screen/findByActor/FindByActorViewModelTest.kt
Labels: refactor
