Repository Paris-Squad-S2/Aflami, pull requests merged in 2025-08, with the labels that each got.

#207 Refactor safe image viewer
  app/release-info.txt
  buildSrc/.kotlin/errors/errors-1752416435436.log
  feature/home/homeUi/build.gradle.kts
  feature/home/homeUi/src/main/java/com/feature/home/homeUi/screen/home/components/HomeSlider.kt
  feature/home/homeUi/src/main/java/com/feature/home/homeUi/screen/home/components/MediaCard.kt
  feature/mediaDetails/mediaDetailsUi/src/main/java/com/feature/mediaDetails/mediaDetailsUi/ui/comon/components/MediaCard.kt
  feature/mediaDetails/mediaDetailsUi/src/main/java/com/feature/mediaDetails/mediaDetailsUi/ui/comon/components/detailsImage/DetailsImage.kt
  feature/search/searchUi/src/main/java/com/feature/search/searchUi/comon/components/MediaCard.kt
  safeimageviewer/src/main/java/com/designSystem/safeimageviewer/GenderClassifier.kt
  safeimageviewer/src/main/java/com/designSystem/safeimageviewer/ImageBlurUtils.kt
  safeimageviewer/src/main/java/com/designSystem/safeimageviewer/NSFWCache.kt
  safeimageviewer/src/main/java/com/designSystem/safeimageviewer/NSFWDetector.kt
  safeimageviewer/src/main/java/com/designSystem/safeimageviewer/SafeImageProcessor.kt
  safeimageviewer/src/main/java/com/designSystem/safeimageviewer/SafeImageViewer.kt
  safeimageviewer/src/main/java/com/designSystem/safeimageviewer/modifier/BlurModifier.kt
  safeimageviewer/src/main/java/com/designSystem/safeimageviewer/utils/blurBitmap.kt
  safeimageviewer/src/main/ml/GenderClass.tflite
Labels: enhancement, bug-fix

#212 Replace UserAuthInterceptor inside the user remote datasource
  app/release-info.txt
  app/src/main/java/com/paris_2/aflami/AuthInterceptor.kt
  app/src/main/java/com/paris_2/aflami/di/NetworkModule.kt
  datasource/remote/user/src/main/java/com/paris_2/datasource/remote/user/UserAuthInterceptor.kt
  feature/profile/profileUi/build.gradle.kts
  feature/profile/profileUi/src/test/java/com/feature/profile/profileUi/screen/myRating/MyRatingViewModelTest.kt
  feature/profile/profileUi/src/test/java/com/feature/profile/profileUi/screen/watchHistory/WatchHistoryViewModelTest.kt
Labels: enhancement, refactor

#224 refactor build gradle
  app/build.gradle.kts
  build.gradle.kts
  buildSrc/src/main/kotlin/Modules.kt
  datasource/local/media/build.gradle.kts
  datasource/local/movie/build.gradle.kts
  datasource/local/tvShow/build.gradle.kts
  datasource/local/user/build.gradle.kts
  datasource/remote/lists/build.gradle.kts
  datasource/remote/media/build.gradle.kts
  datasource/remote/movie/build.gradle.kts
  datasource/remote/tvShow/build.gradle.kts
  datasource/remote/user/build.gradle.kts
  feature/authentication/authenticationUi/build.gradle.kts
  feature/bottomNavBar/bottomNavBarUI/build.gradle.kts
  feature/categories/categoriesUi/build.gradle.kts
  feature/guessGame/guessGameUi/build.gradle.kts
  feature/home/homeUi/build.gradle.kts
  feature/lists/listsUi/build.gradle.kts
  feature/mediaDetails/mediaDetailsUi/build.gradle.kts
  feature/onboarding/onboardingUi/build.gradle.kts
  feature/profile/profileUi/build.gradle.kts
  feature/search/searchUi/build.gradle.kts
  repository/lists/build.gradle.kts
  repository/media/build.gradle.kts
  repository/movie/build.gradle.kts
  repository/tvShows/build.gradle.kts
  repository/user/build.gradle.kts
  settings.gradle.kts
Labels: enhancement

#228 Feature/splash
  app/build.gradle.kts
  app/release-info.txt
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/paris_2/aflami/MainActivity.kt
  app/src/main/res/drawable/aflami_splash.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/themes.xml
  feature/authentication/authenticationUi/src/main/AndroidManifest.xml
  feature/mediaDetails/mediaDetailsUi/src/main/AndroidManifest.xml
  feature/onboarding/onboardingUi/src/main/AndroidManifest.xml
  feature/search/searchUi/src/main/AndroidManifest.xml
  gradle/libs.versions.toml
Labels: feature

#232 Update library versions and consolidate JUnit dependencies
  app/release-info.txt
  datasource/local/movie/build.gradle.kts
  domain/user/build.gradle.kts
  gradle/libs.versions.toml
Labels: enhancement

#241 Refactor signing configuration and update dependencies
  app/build.gradle.kts
  app/release-info.txt
  build.gradle.kts
  buildSrc/src/main/kotlin/SigningExtensions.kt
  gradle/libs.versions.toml
  logger/build.gradle.kts
  logger/src/main/java/com/parise_2/firebase/firebase/FireBaseCrashlyticsLogger.kt
Labels: enhancement

#247 add readme file
  ReadMe.md
Labels: feature

#250 Mood Picker Blured Image Bug
  app/release-info.txt
  feature/home/homeUi/src/main/java/com/feature/home/homeUi/screen/home/HomeScreenUIState.kt
  feature/home/homeUi/src/main/java/com/feature/home/homeUi/screen/home/HomeScreenViewModel.kt
  feature/home/homeUi/src/main/java/com/feature/home/homeUi/screen/home/components/MoodPickerDialog.kt
  feature/home/homeUi/src/test/java/com/feature/home/homeUi/HomeScreenViewModelTest.kt
Labels: bug-fix

#251 refactor/episode
  feature/mediaDetails/mediaDetailsUi/src/main/java/com/feature/mediaDetails/mediaDetailsUi/ui/mapper/UiMapper.kt
  feature/mediaDetails/mediaDetailsUi/src/main/java/com/feature/mediaDetails/mediaDetailsUi/ui/screen/tvShow/details/TvShowDetailsScreen.kt
  feature/mediaDetails/mediaDetailsUi/src/main/java/com/feature/mediaDetails/mediaDetailsUi/ui/screen/tvShow/details/TvShowUiState.kt
Labels: enhancement

#257 Implement System-Aware Dark Theme Handling
  app/release-info.txt
  app/src/main/java/com/paris_2/aflami/MainActivity.kt
  app/src/main/java/com/paris_2/aflami/di/DataSourceModule.kt
  datasource/local/user/src/main/java/com/paris_2/dataSource/local/user/SettingLocalDataSourceImpl.kt
  datasource/local/user/src/test/java/com/paris_2/dataSource/local/user/SettingLocalDataSourceImplTest.kt
Labels: bug-fix, refactor

#255 refactor/statusPadding&-getPoints
  app/release-info.txt
  app/src/main/java/com/paris_2/aflami/di/UseCaseModule.kt
  datasource/local/guessGame/src/main/java/com/datasource/local/guessGame/dao/GamePointsDao.kt
  datasource/local/guessGame/src/main/java/com/datasource/local/guessGame/datasource/GamePointsLocalDataSourceImpl.kt
  datasource/local/guessGame/src/test/java/com/datasource/local/guessGame/datasource/GamePointsLocalDataSourceImplTest.kt
  domain/guessGame/build.gradle.kts
  domain/guessGame/src/main/java/com/paris_2/domain/game/repositories/GamePointsRepository.kt
  domain/guessGame/src/main/java/com/paris_2/domain/game/usecases/GetUserPointUseCase.kt
  domain/guessGame/src/main/java/com/paris_2/domain/game/usecases/UpdatePointsUseCase.kt
  domain/guessGame/src/main/java/com/paris_2/domain/game/usecases/UseHintUseCase.kt
  domain/guessGame/src/test/java/com/paris_2/domain/game/usecases/GetUserPointUseCaseTest.kt
  domain/guessGame/src/test/java/com/paris_2/domain/game/usecases/UpdatePointsUseCaseTest.kt
  domain/guessGame/src/test/java/com/paris_2/domain/game/usecases/UseHintUseCaseTest.kt
  feature/guessGame/guessGameUi/src/main/java/com/feature/guessGame/guessGameUi/common/BaseViewModel.kt
  feature/guessGame/guessGameUi/src/main/java/com/feature/guessGame/guessGameUi/screen/guessGameScreen/GuessGameScreenViewModel.kt
  feature/guessGame/guessGameUi/src/main/java/com/feature/guessGame/guessGameUi/screen/guessQuestionScreen/GuessQuestionViewModel.kt
  feature/guessGame/guessGameUi/src/main/java/com/feature/guessGame/guessGameUi/screen/guessbyimage/GuessByImageViewModel.kt
  feature/guessGame/guessGameUi/src/test/java/com/feature/guessGame/guessGameUi/screen/guessGameScreen/GuessGameScreenViewModelTest.kt
  feature/mediaDetails/mediaDetailsUi/src/main/java/com/feature/mediaDetails/mediaDetailsUi/ui/navigation/MediaDetailsNavigatorEntryPoint.kt
  feature/mediaDetails/mediaDetailsUi/src/main/java/com/feature/mediaDetails/mediaDetailsUi/ui/screen/movie/details/MovieDetailsViewModel.kt
  feature/mediaDetails/mediaDetailsUi/src/main/java/com/feature/mediaDetails/mediaDetailsUi/ui/screen/movie/details/MovieUiState.kt
  feature/profile/profileUi/src/main/java/com/feature/profile/profileUi/common/BaseViewModel.kt
  feature/profile/profileUi/src/main/java/com/feature/profile/profileUi/screen/ProfileViewModel.kt
  feature/profile/profileUi/src/main/java/com/feature/profile/profileUi/screen/myRating/MyRatingScreen.kt
  feature/profile/profileUi/src/main/java/com/feature/profile/profileUi/screen/myRating/MyRatingUiState.kt
  feature/profile/profileUi/src/main/java/com/feature/profile/profileUi/screen/myRating/MyRatingViewModel.kt
  feature/profile/profileUi/src/main/java/com/feature/profile/profileUi/screen/watchHistory/WatchHistoryScreen.kt
  feature/profile/profileUi/src/main/java/com/feature/profile/profileUi/screen/watchHistory/WatchHistoryUiState.kt
  feature/profile/profileUi/src/main/java/com/feature/profile/profileUi/screen/watchHistory/WatchHistoryViewModel.kt
  repository/guessGame/src/main/java/com/repository/guessgame/datasource/local/GamePointsLocalDataSource.kt
  repository/guessGame/src/main/java/com/repository/guessgame/repository/GamePointsRepositoryImpl.kt
  repository/guessGame/src/test/java/com/repository/guessgame/repository/ActorPopularityRepositoryImplTest.kt
  repository/guessGame/src/test/java/com/repository/guessgame/repository/GamePointsRepositoryImplTest.kt
Labels: bug-fix, refactor

#269 refactor code
  app/build.gradle.kts
  build.gradle.kts
  datasource/local/categories/.gitignore
  datasource/local/categories/build.gradle.kts
  datasource/local/categories/src/main/java/com/datasource/local/categories/MyClass.kt
  datasource/local/guessGame/src/main/java/com/datasource/local/guessGame/GuessGameDatabase.kt
  datasource/local/media/src/main/java/com/datasource/local/media/MediaDatabase.kt
  datasource/remote/categories/.gitignore
  datasource/remote/categories/build.gradle.kts
  datasource/remote/categories/src/main/java/com/datasource/remote/categories/MyClass.kt
  datasource/remote/media/src/main/java/com/repository/media/MediaRemoteDataSourceImpl.kt
  datasource/remote/media/src/test/java/com/repository/media/MediaDataSourceImplTest.kt
  datasource/remote/user/src/main/java/com/paris_2/datasource/remote/user/UserAuthInterceptor.kt
  datasource/remote/user/src/main/java/com/paris_2/datasource/remote/user/UserRemoteDataSourceImpl.kt
  repository/guessGame/src/main/java/com/repository/guessgame/repository/GamePointsRepositoryImpl.kt
  repository/lists/src/main/java/com/repository/lists/ListsRepositoryImpl.kt
  repository/media/src/main/java/com/repository/media/datasource/remote/TvShowDetailsRemoteDataSource.kt
  repository/media/src/main/java/com/repository/media/mapper/MediaMapper.kt
  repository/media/src/main/java/com/repository/media/mapper/MovieMapper.kt
  repository/media/src/main/java/com/repository/media/mapper/TvShowsMapper.kt
  repository/media/src/main/java/com/repository/media/models/remote/media/category/MovieByCategoryDto.kt
  repository/media/src/main/java/com/repository/media/models/remote/media/category/ResultDto.kt
  repository/media/src/main/java/com/repository/media/models/remote/media/category/TvResultDto.kt
  repository/media/src/main/java/com/repository/media/models/remote/media/category/TvShowByCategoryDto.kt
  repository/media/src/main/java/com/repository/media/models/remote/media/profile/RatedMoviesDto.kt
  repository/media/src/main/java/com/repository/media/models/remote/media/profile/RatedTvShowDtoo.kt
  repository/media/src/main/java/com/repository/media/models/remote/media/profile/TvShowResult.kt
  repository/media/src/test/java/com/repository/media/repository/MediaRepositoryImplTest.kt
  repository/user/src/main/java/com/paris_2/repository/user/repository/SettingRepositoryImpl.kt
  repository/user/src/main/java/com/paris_2/repository/user/repository/UserRepositoryImpl.kt
  settings.gradle.kts
Labels: enhancement

#271 Refactor/guess game logic
  app/release-info.txt
  app/src/main/java/com/paris_2/aflami/di/UseCaseModule.kt
  domain/guessGame/src/main/java/com/paris_2/domain/game/usecases/GetUserPointUseCase.kt
  domain/guessGame/src/test/java/com/paris_2/domain/game/usecases/GetUserPointUseCaseTest.kt
  feature/guessGame/guessGameUi/build.gradle.kts
  feature/guessGame/guessGameUi/src/main/java/com/feature/guessGame/guessGameUi/HintUsageResult.kt
  feature/guessGame/guessGameUi/src/main/java/com/feature/guessGame/guessGameUi/common/components/GuessGame.kt
  feature/guessGame/guessGameUi/src/main/java/com/feature/guessGame/guessGameUi/screen/guessGameScreen/GuessGameScreen.kt
  feature/guessGame/guessGameUi/src/main/java/com/feature/guessGame/guessGameUi/screen/guessGameScreen/GuessGameScreenUiState.kt
  feature/guessGame/guessGameUi/src/main/java/com/feature/guessGame/guessGameUi/screen/guessGameScreen/GuessGameScreenViewModel.kt
  feature/guessGame/guessGameUi/src/main/java/com/feature/guessGame/guessGameUi/screen/guessQuestionScreen/GuessQuestionInteractionListener.kt
  feature/guessGame/guessGameUi/src/main/java/com/feature/guessGame/guessGameUi/screen/guessQuestionScreen/GuessQuestionScreen.kt
  feature/guessGame/guessGameUi/src/main/java/com/feature/guessGame/guessGameUi/screen/guessQuestionScreen/GuessQuestionViewModel.kt
  feature/guessGame/guessGameUi/src/main/java/com/feature/guessGame/guessGameUi/screen/guessbyimage/GuessByImageInteractionListener.kt
  feature/guessGame/guessGameUi/src/main/java/com/feature/guessGame/guessGameUi/screen/guessbyimage/GuessByImageScreen.kt
  feature/guessGame/guessGameUi/src/main/java/com/feature/guessGame/guessGameUi/screen/guessbyimage/GuessByImageViewModel.kt
  feature/guessGame/guessGameUi/src/main/java/com/feature/guessGame/guessGameUi/screen/resultScreen/ResultInteractionListener.kt
  feature/guessGame/guessGameUi/src/main/java/com/feature/guessGame/guessGameUi/screen/resultScreen/ResultScreen.kt
  feature/guessGame/guessGameUi/src/main/java/com/feature/guessGame/guessGameUi/screen/resultScreen/ResultViewModel.kt
  feature/guessGame/guessGameUi/src/test/java/com/feature/guessGame/guessGameUi/screen/guessGameScreen/GuessGameScreenViewModelTest.kt
  feature/guessGame/guessGameUi/src/test/java/com/feature/guessGame/guessGameUi/screen/guessQuestionScreen/GuessQuestionViewModelTest.kt
  feature/guessGame/guessGameUi/src/test/java/com/feature/guessGame/guessGameUi/screen/resultScreen/ResultViewModelTest.kt
  feature/profile/profileUi/src/main/java/com/feature/profile/profileUi/screen/ProfileScreenUiState.kt
  feature/profile/profileUi/src/main/java/com/feature/profile/profileUi/screen/ProfileViewModel.kt
  feature/profile/profileUi/src/test/java/com/feature/profile/profileUi/screen/ProfileViewModelTest.kt
  repository/guessGame/src/main/java/com/repository/guessgame/entity/UserGamePointsEntity.kt
  repository/guessGame/src/main/java/com/repository/guessgame/repository/GamePointsRepositoryImpl.kt
  repository/user/src/main/java/com/paris_2/repository/user/repository/UserRepositoryImpl.kt
Labels: bug-fix

#301 feature/remove-movie-from-list
  app/release-info.txt
  app/src/main/java/com/paris/aflami/di/UseCaseModule.kt
  domain/lists/src/main/java/com/paris/domain/lists/useCase/GetMovieListIdUseCase.kt
  domain/lists/src/test/java/com/paris/domain/lists/useCase/GetMovieListIdUseCaseTest.kt
  feature/mediaDetails/mediaDetailsUi/src/main/java/com/feature/mediaDetails/mediaDetailsUi/ui/comon/components/MovieTopComponent.kt
  feature/mediaDetails/mediaDetailsUi/src/main/java/com/feature/mediaDetails/mediaDetailsUi/ui/screen/movie/details/MovieDetailsScreenInteractionListener.kt
  feature/mediaDetails/mediaDetailsUi/src/main/java/com/feature/mediaDetails/mediaDetailsUi/ui/screen/movie/details/MovieDetailsViewModel.kt
  feature/mediaDetails/mediaDetailsUi/src/main/res/values-ar/strings.xml
  feature/mediaDetails/mediaDetailsUi/src/main/res/values/strings.xml
  feature/mediaDetails/mediaDetailsUi/src/test/java/com/feature/mediaDetails/mediaDetailsUi/ui/screen/details/MovieDetailsViewModelTest.kt
Labels: feature
